#define SECRET_MQTT_USERNAME "YOUR_MQTT_USERNAME"   // YOUR_MQTT_USERNAME 
#define SECRET_MQTT_CLIENT_ID "YOUR_MQTT_CLIENT_ID" // YOUR_MQTT_CLIENT_ID 
#define SECRET_MQTT_PASSWORD "YOUR_MQTT_PASSWORD"   // YOUR_MQTT_PASSWORD

#define SECRET_WIFI_NAME "YOUR_WIFI_NAME"           // YOUR_WIFI_NAME
#define SECRET_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"   // YOUR_WIFI_PASSWORD
#define CHANNEL_ID "YOUR_CHANNEL_ID"                // YOUR_CHANNEL_ID
